// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Days.iOS
{
	public partial class AddCardView : UIViewController
	{
		public AddCardView(IntPtr handle) : base(handle)
		{

		}
	}
}
