// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Days.iOS
{
	public partial class CardViewController : UIViewController
	{
		public Card DisplayedCard { get; set; }

		public CardViewController(IntPtr handle) : base(handle)
		{
		}
	}
}
