// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Days.iOS
{
	public partial class DayViewController : UIViewController
	{
		public DayViewController(IntPtr handle) : base(handle)
		{
		}
	}
}
